language: node_js
node_js:
  - "12.13"
cache: npm

install:
  - npm install

script:
  - npm test
  - npm run build
  - npx next export

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages